[develop] CD 워크플로우 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,7 +21,7 @@ jobs:
       # 3. Create .env file
       - name: Create .env file
         run: |
-          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
+          echo "${{ secrets.ENV_FILE_CONTENT }}" > src/main/resources/.env
 
       # 4. Set up JDK and Build JAR
       - name: Set up JDK 17
@@ -50,7 +50,7 @@ jobs:
         run: |
           set -e
           IMAGE_TAG=$(date +%Y%m%d%H%M%S)
-          echo "Building Docker image with platform linux/amd64..."
+          echo "Building Docker image..."
           docker build --platform linux/amd64 --build-arg JAR_FILE=build/libs/daengle-server-0.0.1-SNAPSHOT.jar -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
           docker tag ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:latest
           docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
@@ -78,14 +78,14 @@ jobs:
           echo "=== Stopping and removing existing container ==="
           if docker ps -q --filter "name=spring-app" > /dev/null; then
             echo "Stopping existing container..."
-            docker stop spring-app || true
-            docker rm spring-app || true
+            docker stop spring-app || { echo "Failed to stop container"; exit 1; }
+            docker rm spring-app || { echo "Failed to remove container"; exit 1; }
           else
-            echo "No existing container to stop. Proceeding with deployment."
+            echo "No existing container to stop."
           fi
 
           echo "=== Running new container ==="
-          docker run --env-file .env -d --name spring-app -p 80:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker run failed"; exit 1; }
+          docker run -d --name spring-app -p 80:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker run failed"; exit 1; }
 
           echo "=== Verifying the new container ==="
           sleep 10 # Allow container to initialize
