[develop] 워크플로우 도커 이미지 누적 처리

diff --git a/.github/workflows/dev-deploy.yml b/.github/workflows/dev-deploy.yml
--- a/.github/workflows/dev-deploy.yml
+++ b/.github/workflows/dev-deploy.yml
@@ -22,8 +22,7 @@ jobs:
           - name: daengle-groomer
             path: daengle-groomer-api
             ssh_host_var: SSH_GROOMER_HOST
-      max-parallel: 1  # 병렬 실행 수를 1로 제한하여 순차적으로 실행
-
+      max-parallel: 1
 
     env:
       SSH_USER: ${{ secrets.SSH_USER }}
@@ -118,6 +117,16 @@ jobs:
           MODULE=${{ matrix.module.name }}
           IMAGE_TAG=${IMAGE_TAG}
           CONTAINER_NAME="${{matrix.module.name}}-container"
+    
+          echo "=== Cleaning up old Docker images ==="
+          # 최신 6개 이미지를 제외한 나머지 삭제
+          IMAGE_COUNT=$(docker images -q | wc -l)
+          if [ "$IMAGE_COUNT" -gt 6 ]; then
+          echo "Deleting old images, keeping the latest 6..."
+          docker images -q | tail -n +7 | xargs -r docker rmi -f
+          else
+          echo "No old images to delete. Current image count: $IMAGE_COUNT"
+          fi
           
           # Pull latest image
           docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker pull failed"; exit 1; }
@@ -125,11 +134,11 @@ jobs:
           echo "=== Verifying Docker images ==="
           docker images  
 
-          echo "=== Stopping and removing existing container ==="
-          docker ps --filter "name=$CONTAINER_NAME" | grep $CONTAINER_NAME && docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME || echo "No running container to stop."
-          docker ps -a --filter "name=$CONTAINER_NAME" -q | xargs -r docker stop | xargs -r docker rm || echo "No running container to stop."
-
-          echo "=== Running new container ==="
-          docker run -d --name $CONTAINER_NAME -p 8080:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker run failed"; exit 1; }
-
-          echo "=== Deployment completed successfully ==="
+#          echo "=== Stopping and removing existing container ==="
+#          docker ps --filter "name=$CONTAINER_NAME" | grep $CONTAINER_NAME && docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME || echo "No running container to stop."
+#          docker ps -a --filter "name=$CONTAINER_NAME" -q | xargs -r docker stop | xargs -r docker rm || echo "No running container to stop."
+#
+#          echo "=== Running new container ==="
+#          docker run -d --name $CONTAINER_NAME -p 8080:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker run failed"; exit 1; }
+#
+#          echo "=== Deployment completed successfully ==="
